name: apklis_license_validator
description: Paquete de Flutter para el chequeo y compra de licencias de Apklis.
publish_to: "none"

flutter:
  plugin:
    platforms:
      android:
        package: cu.uci.android.apklis_license_validator
        pluginClass: ApklisLicenseValidatorPlugin

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
